using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;


namespace FileBasedApp.Toolkit.SourceGenerators;

/// <summary>
/// A sample source generator that creates a custom report based on class properties. The target class should be annotated with the 'Generators.ReportAttribute' attribute.
/// When using the source code as a baseline, an incremental source generator is preferable because it reduces the performance overhead.
/// </summary>
[Generator]
public class SourceGeneratorWithAttributes : IIncrementalGenerator
{
    private const string Namespace = "FileBasedApp.Toolkit.SourceGenerators";
    private const string AttributeName = "DirectoryPathAttribute";

    private const string AttributeSourceCode = $@"// <auto-generated/>

using FileBasedApp.Toolkit;

namespace {Namespace}
{{
    [System.AttributeUsage(System.AttributeTargets.Property)]
    public class {AttributeName} : System.Attribute
    {{
	    private readonly PredefinedRootPath predefinedRoot;

	    public {AttributeName}(bool allowEmpty, bool shouldExist, PredefinedRootPath predefinedRoot)
	    {{
		    AllowEmpty = allowEmpty;
		    ShouldExist = shouldExist;
		    PredefinedRoot = predefinedRoot;
	    }}

	    public bool AllowEmpty {{ get; }}
	    public bool ShouldExist {{ get; }}
        public PredefinedRootPath PredefinedRoot {{ get; }}
    }}
}}";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Add the marker attribute to the compilation.
        context.RegisterPostInitializationOutput(ctx => ctx.AddSource(
            "DirectoryPathAttribute.g.cs",
            SourceText.From(AttributeSourceCode, Encoding.UTF8)));

        // Filter classes annotated with the [Report] attribute. Only filtered Syntax Nodes can trigger code generation.
        var provider = context.SyntaxProvider
            .CreateSyntaxProvider(
                (s, _) => s is PropertyDeclarationSyntax,
                (ctx, _) => GetPropertyDeclarationForSourceGen(ctx))
            .Where(t => t.reportAttributeFound)
            .Select((t, _) => t.Item1);

        // Generate the source code.
        context.RegisterSourceOutput(context.CompilationProvider.Combine(provider.Collect()),
            ((ctx, t) => GenerateCode(ctx, t.Left, t.Right)));
    }

    /// <summary>
    /// Checks whether the Node is annotated with the [Report] attribute and maps syntax context to the specific node type (ClassDeclarationSyntax).
    /// </summary>
    /// <param name="context">Syntax context, based on CreateSyntaxProvider predicate</param>
    /// <returns>The specific cast and whether the attribute was found.</returns>
    private static (PropertyDeclarationSyntax, bool reportAttributeFound) GetPropertyDeclarationForSourceGen(
        GeneratorSyntaxContext context)
    {
        var propertyDeclarationSyntax = (PropertyDeclarationSyntax) context.Node;

        // Go through all attributes of the class.
        foreach (AttributeListSyntax attributeListSyntax in propertyDeclarationSyntax.AttributeLists)
        foreach (AttributeSyntax attributeSyntax in attributeListSyntax.Attributes)
        {
            if (context.SemanticModel.GetSymbolInfo(attributeSyntax).Symbol is not IMethodSymbol attributeSymbol)
                continue; // if we can't get the symbol, ignore it

            string attributeName = attributeSymbol.ContainingType.ToDisplayString();

            // Check the full name of the [Report] attribute.
            if (attributeName == $"{Namespace}.{AttributeName}")
                return (propertyDeclarationSyntax, true);
        }

        return (propertyDeclarationSyntax, false);
    }

    /// <summary>
    /// Generate code action.
    /// It will be executed on specific nodes (ClassDeclarationSyntax annotated with the [Report] attribute) changed by the user.
    /// </summary>
    /// <param name="context">Source generation context used to add source files.</param>
    /// <param name="compilation">Compilation used to provide access to the Semantic Model.</param>
    /// <param name="propertyDeclarations">Nodes annotated with the [Report] attribute that trigger the generate action.</param>
    private void GenerateCode(SourceProductionContext context, Compilation compilation,
        ImmutableArray<PropertyDeclarationSyntax> propertyDeclarations)
    {
        // Go through all filtered class declarations.
        foreach (var propertyDeclaration in propertyDeclarations)
        {
            // We need to get semantic model of the class to retrieve metadata.
            var semanticModel = compilation.GetSemanticModel(propertyDeclaration.SyntaxTree);

            // Symbols allow us to get the compile-time information.
            if (semanticModel.GetDeclaredSymbol(propertyDeclaration) is not IPropertySymbol propertySymbol)
                continue;

            var namespaceName = propertySymbol.ContainingNamespace.IsGlobalNamespace ? null : propertySymbol.ContainingNamespace.ToDisplayString();

            // 'Identifier' means the token of the node. Get class name from the syntax node.
            var propertyName = propertyDeclaration.Identifier.Text;
            var classMember = propertySymbol.ContainingType;
            
            var attribute = propertySymbol.GetAttributes()
                .FirstOrDefault(a => a.AttributeClass?.Name == AttributeName);
            if (attribute == null)
                continue;

            if (attribute.ApplicationSyntaxReference?.GetSyntax() is not AttributeSyntax attributeSyntax)
            {
                continue;
            }
            
            
            
            

            // Build up the source code
            var code = $@"// <auto-generated/>

using FileBasedApp.Toolkit;

{(namespaceName == null ? "" : ("namespace " + namespaceName + ";"))}

public partial class {classMember.Name}
{{
    public TruePath.AbsolutePath {propertyName}_Path => TryGetDirectory({propertyName},  {attributeSyntax.ArgumentList!.Arguments[2].Expression.ToFullString()}, allowEmpty: {attributeSyntax.ArgumentList!.Arguments[0].Expression.ToFullString()}, shouldExist: {attributeSyntax.ArgumentList!.Arguments[1].Expression.ToFullString()});
}}
";

            // Add the source code to the compilation.
            context.AddSource($"{classMember.Name}_{propertyName}.g.cs", SourceText.From(code, Encoding.UTF8));
        }
    }
}