<?xml version="1.0" encoding="utf-8"?><Project>
  <PropertyGroup>
      <VersionPrefix>0.20.1</VersionPrefix>
      <VersionSuffix>alpha-02</VersionSuffix>      
      <IsPackable>false</IsPackable>
      <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
</Project>