<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>    
    <IsPackable>true</IsPackable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Title>Opiniated helpers for FileBasedApps</Title>
    <Description>Opiniated helpers for a FileBaseApp. Based on TruePath, SimpleExec and Spectre.Console.Cli</Description>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <TargetFrameworks>net10.0;net8.0</TargetFrameworks>
    <RepositoryUrl>https://github.com/jeppevammenkristensen/FileBasedApp.Toolkit/tree/main/Source/FileBasedApp/FileBasedApp.Toolkit</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression> 
    <VersionPrefix>0.17.1</VersionPrefix>
    <VersionSuffix>alpha-01</VersionSuffix>
    <PackageReleaseNotes>
      - Adjusted package references
    </PackageReleaseNotes>
    <LangVersion>14</LangVersion>    
  </PropertyGroup>
  
  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <!-- Ensure PDBs are produced and carried along for local debug deploy/publish -->
    <DebugType>full</DebugType>
    <DebugSymbols>true</DebugSymbols>        
  </PropertyGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
  
  <ItemGroup>    
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="3.11.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
<!--    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.0.0" />-->
<!--    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.SourceGenerators.Testing.XUnit" Version="1.1.2" />-->
<!--    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="5.0.0" />-->
<!--    <PackageReference Include="NETStandard.Library" Version="2.0.3" />-->
    <PackageReference Include="SimpleExec" Version="13.0.0" />
    <PackageReference Include="Spectre.Console.Cli" Version="0.53.1" />
    <PackageReference Include="TestableIO.System.IO.Abstractions.Wrappers" Version="22.1.0" />
    <PackageReference Include="TruePath.TestableIO.System.IO" Version="0.16.0" />
    <PackageReference Include="TruePath" Version="1.12.0" />
    
  </ItemGroup> 
 
  <ItemGroup>
    <InternalsVisibleTo Include="FileBasedApp.Toolkit.Tests" />
  </ItemGroup> 
 
  

</Project>
