<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <IsPackable>false</IsPackable>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    <ItemGroup>
      <ProjectReference Include="..\FileBasedApp\FileBasedApp.Toolkit\FileBasedApp.Toolkit.csproj" />
    </ItemGroup>
    <ItemGroup>
      <PackageReference Include="Dumpify" Version="0.7.0" />
        <PackageReference Include="Spectre.Console" Version="0.55.0" />
      <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.6" />
      <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.6" />
      <PackageReference Include="Spectre.Console.Json" Version="0.55.0" />
    </ItemGroup>

</Project>
