<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <PackageType>Template</PackageType>
        <PackageId>FileBasedApp.Toolkit.Template</PackageId>
        <Authors>Jeppe Roi Kristensen</Authors>
        <Title>File-Based App Templates</Title>
        <Description>A simple file-based application class template. using the FileBasedApp.Toolkit</Description>
        <PackageTags>filebased</PackageTags>        
        <IncludeContentInPack>true</IncludeContentInPack>
        <IncludeBuildOutput>false</IncludeBuildOutput>
        <ContentTargetFolders>content</ContentTargetFolders>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageReleaseNotes>Fixed template to correctly return error code</PackageReleaseNotes>
        <NoWarn>$(NoWarn);NU5128</NoWarn>
        
    </PropertyGroup>

    <ItemGroup>
        <None Include="README.md" Pack="true" PackagePath="\"/>

        <Content Include="FileBasedAppTemplate\**\*" Exclude="**\bin\**;**\obj\**"/>
        <Compile Remove="**\*"/>
    </ItemGroup>

</Project>