<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <VersionPrefix>0.18.0</VersionPrefix>
        <VersionSuffix>alpha-01</VersionSuffix>
        <Description>Helpers for dotnet specific operations</Description>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\FileBasedApp.Toolkit\FileBasedApp.Toolkit.csproj" />
    </ItemGroup>

</Project>
