<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>true</IsPackable>
        <Title>Dotnet CLI helpers for FileBasedApps</Title>
        <Description>Fluent builders and recipes for dotnet CLI commands (pack, nuget push, package search).</Description>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <RepositoryUrl>https://github.com/jeppevammenkristensen/FileBasedApp.Toolkit</RepositoryUrl>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageIcon>floppy-disc.png</PackageIcon>
        <PackageReleaseNotes>            
        </PackageReleaseNotes>
    </PropertyGroup>

    <ItemGroup>
        <None Include="README.md" Pack="true" PackagePath="\" />
        <None Include="..\floppy-disc.png" Pack="true" PackagePath="\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\FileBasedApp.Toolkit\FileBasedApp.Toolkit.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="NuGet.Versioning" />
    </ItemGroup>

</Project>
